.dev3-base: &dev3-base
    hostname: deploy@dev3.mir24.tv
    app_name: dev7
    app_base_path: /var/www/mir24-app
    stage: prod
    keep_releases: 5
    http_user: www-data
    cleanup_use_sudo: true
    forwardAgent: true
    multiplexing: true
    sshOptions:
        StrictHostKeyChecking: no

.prod-settings: &prod-settings
    db_app_host: 192.168.227.23
    db_app_user: mir24_admin
    db_app_pass: password
    env_example_file: "{{release_path}}/.env.example"
    inject_env:
        APP_KEY: base64:key
        DB_HOST: "{{db_app_host}}"
        DB_DATABASE: "{{db_app_name}}"
        DB_USERNAME: "{{db_app_user}}"
        DB_PASSWORD: "{{db_app_pass}}"
        SPHINX_HOST: '127.0.0.1'
        SPHINX_PORT: 9312
        SPHINX_PREFIX: mir24_
        CACHE_ENABLED: 'false'
        CDN_IMAGES_URL: '""'
        MAIL_DRIVER: 'smtp'
        MAIL_HOST: 'mail.mirtv.ru'
        MAIL_PORT: 25
        MAIL_USERNAME: 'support@mir24.tv'
        MAIL_PASSWORD: 'password'
        MAIL_ENCRYPTION: 'null'
        CACHE_WARMMARKER: 'hot'
        NOCAPTCHA_SECRET: 'secret'
        NOCAPTCHA_SITEKEY: 'key'
        VIDEO_VAST_TAG: '//moevideo.biz/vast?ref=mir24.tv&impressionAfterPaid=1&referrer=https%3A%2F%2Fmir24.tv'
        CACHE_DRIVER: 'memcached'
        QUEUE_DRIVER: 'database'
        PRIVATE_KEY: 'key'
        PUBLIC_KEY: 'key'
        GCM_SERVER_KEY: 'key'
        SUBJECT: 'mir24.tv'
        FACEBOOK_ENABLED: 'false'
        FACEBOOK_APP_ID: 'appid'
        FACEBOOK_APP_SECRET: 'secret'
        FACEBOOK_GRAPH_VERSION: 'v2.10'
        FACEBOOK_PERMANENT_ACCESS_TOKEN: 'token'
        FACEBOOK_PAGE_ID: 'pageid'
        TWITTER_ENABLED: 'true'
        TWITTER_CONSUMER_KEY: 'key'
        TWITTER_CONSUMER_SECRET: 'secret'
        TWITTER_ACCESS_TOKEN: 'token'
        TWITTER_ACCESS_TOKEN_SECRET: 'secret'
        VK_API_VERSION: '5.5'
        VK_APP_TOKEN: 'token'
        VK_OWNER_ID: 'ownerid'
        FRONT_ROUTE: 'https://dev-release.mir24.tv'
    inject_env_switched:
        CACHE_ENABLED: 'true'
        CDN_IMAGES_URL: 'https://imgtest.mir24.tv'
        FRONT_ROUTE: 'https://mir24.tv'


prod-services:
    <<: *dev3-base
    <<: *prod-settings
    roles: [service-scripts]
    repository: git@github.com:MIR24/mir24tv-service-scripts.git
    deploy_path: "{{app_base_path}}/mir24tv-service-scripts"
    sphinx_conf_dest: "{{release_path}}/build/sphinx.conf"
    supervisor_params:
        prefix: "{{app_name}}_"
        base_dir: "{{app_base_path}}/editors.mir24.tv/current/"
        log_dir: "{{app_base_path}}/editors.mir24.tv/current/storage/logs/supervisor.log"
    mount_files:
        - "{{release_path}}/sphinxsearch/sphinx.conf:{{release_path}}/build/sphinx.conf"
        - "{{release_path}}/supervisord/supervisor.conf:{{release_path}}/build/supervisor.conf"
    rsync:
        options: []
        flags: rzuEa
        include: []
        include-file:
        exclude: []
        exclude-file:
        filter: []
        filter-file:
        filter-perdir:

prod-frontend:
    <<: *dev3-base
    <<: *prod-settings
    roles: [frontend-server]
    repository: git@github.com:MIR24/frontend-server.git
    composer_action: install
    writable_mode: chown
    writable_use_sudo: true
    writable_dirs: [bootstrap/cache, storage, public/sitemaps]
    shared_dirs: [storage/framework/sessions]
    shared_files: [storage/.htpasswd]
    deploy_path: "{{app_base_path}}/mir24.tv"
    uploaded_path: "{{app_base_path}}/editors.mir24.tv/shared/public/uploaded"
    clear_paths:
        - .env.example
        - phpunit.xml
        - README.md
        - server.php
        - travis.yml
    rsync:
        options: []
        flags: rzuEa
        include: []
        include-file:
        exclude: []
        exclude-file:
        filter: []
        filter-file:
        filter-perdir:
    db_source_host: 192.168.227.31
    db_source_name: mir24_dep_26_Mar_14_19
    db_source_user: db_source_user
    db_source_pass: db_source_pass
    db_dep_user: deploy
    db_dep_pass: deploy_user_pass
    dump_file: /home/deploy/mir24_7.sql
#    deploy_permissions:
#        - 'sudo chown -R deploy:www-data ./'
#        - 'sudo chmod 770 -R ./.git ./bootstrap/cache ./public/uploaded ./public/sitemaps ./storage'
#        - 'find .  -not -path "./.git" -not -path "./bootstrap/cache" -not -path "./public/uploaded" -not -path "./public/sitemaps" -not -path "./storage" -not -path "./node_modules" -exec sudo chmod 750 {} \;'

prod-backend:
    <<: *dev3-base
    <<: *prod-settings
    roles: [backend-server]
    repository: git@github.com:MIR24/backend-server.git
    composer_action: update
    writable_mode: chown
    writable_use_sudo: true
    writable_dirs: [public/uploaded, storage]
    shared_dirs: [public/uploaded, storage/framework/sessions]
    shared_files: []
    deploy_path: "{{app_base_path}}/editors.mir24.tv"
    rsync_marker: /home/rsync-dev/mount-marker
    rsync_src: /home/rsync-dev1
    rsync_dest: "{{app_base_path}}/editors.mir24.tv/shared/public/uploaded"
    rsync:
        options: []
        flags: rzuEa
        include: []
        include-file:
        exclude: []
        exclude-file:
        filter: []
        filter-file:
        filter-perdir:
 #   deploy_permissions:
 #       - 'sudo chown -R deploy:www-data ./'
 #       - 'sudo chmod 770 -R ./.git ./storage'
 #       - 'find .  -not -path "./.git" -not -path "./storage" -exec sudo chmod 750 {} \;'

prod-backend-client:
    <<: *dev3-base
    roles: [backend-client]
    repository: git@github.com:MIR24/backend-client.git
    deploy_path: "{{app_base_path}}/backend-client"
    rsync_src: "{{release_path}}/build"
    rsync_dest_base: "{{app_base_path}}/editors.mir24.tv"
    rsync_dest_relative: public
    rsync:
        options: []
        flags: rzuEa
        include: []
        include-file:
        exclude: []
        exclude-file:
        filter: []
        filter-file:
        filter-perdir:

prod-photobank-client:
    <<: *dev3-base
    roles: [photobank-client]
    repository: git@github.com:MIR24/photobank-searchkit.git
    branch: external-client-dev
    deploy_path: "{{app_base_path}}/photobank-client"
    rsync_src: "{{release_path}}/dist"
    rsync_dest_base: "{{app_base_path}}/editors.mir24.tv"
    rsync_dest_relative: public/ftb
    rsync:
        options: []
        flags: rzE
        include: []
        include-file:
        exclude: []
        exclude-file:
        filter: []
        filter-file:
        filter-perdir:
