test-frontend:
    hostname: dev7
    local: true
    stage: test
    roles: test
    keep_releases: 2
    repository: git@github.com:MIR24/frontend-server.git
    composer_action: update
    http_user: www-data
    deploy_path: /home/www/dev7.mir24.tv/mir24.tv
    uploaded_path: /home/www/dev7.mir24.tv/editors.mir24.tv/shared/public/uploaded
    dbhost: 127.0.0.1
    dbname: mir24_7
    dbuser: root
    dbpass: example
    dump_file: /home/www/dev7.mir24.tv/mir24_7.sql
    env_example_file: /home/www/dev7.mir24.tv/.env.frontend

test-backend:
    hostname: dev7
    local: true
    stage: test
    roles: test
    keep_releases: 2
    repository: git@github.com:MIR24/backend-server.git
    composer_action: update
    http_user: www-data
    writable_chmod_mode: true
    writable_chmod_recursive: true
    writable_dirs: [public/uploaded, storage/logs]
    deploy_path: /home/www/dev7.mir24.tv/editors.mir24.tv
    shared_dirs: [public/uploaded]
    writable: [public/uploaded]
    env_example_file: /home/www/dev7.mir24.tv/.env.backend

test-backend-client:
    hostname: dev7
    local: true
    stage: test
    roles: test
    keep_releases: 2
    repository: git@github.com:MIR24/backend-client.git
    http_user: www-data
    deploy_path: /home/www/dev7.mir24.tv/backend-client
    rsync_src: /home/www/dev7.mir24.tv/backend-client/release/build
    rsync_dest: /home/www/dev7.mir24.tv/editors.mir24.tv/release/public
    rsync:
        options: []
        flags: rzuEa
        include: []
        include-file:
        exclude: []
        exclude-file:
        filter: []
        filter-file:
        filter-perdir:

test-photobank-client:
    hostname: dev7
    local: true
    stage: test
    roles: test
    keep_releases: 2
    repository: git@github.com:MIR24/photobank-searchkit.git
    branch: external-client-dev
    http_user: www-data
    deploy_path: /home/www/dev7.mir24.tv/photobank-client
    rsync_src: /home/www/dev7.mir24.tv/photobank-client/release/dist
    rsync_dest: /home/www/dev7.mir24.tv/editors.mir24.tv/release/public/ftb
    rsync:
        options: [delete]
        flags: rzE
        include: []
        include-file:
        exclude: []
        exclude-file:
        filter: []
        filter-file:
        filter-perdir:

prod-frontend:
    hostname: dev3.mir24.tv
    user: barantaran
    stage: test
    roles: test
    keep_releases: 2
    repository: git@github.com:MIR24/frontend-server.git
    branch: master
    composer_action: install
    http_user: www-data
    deploy_path: /var/www/mir24-app/mir24.tv
    uploaded_path: /var/www/mir24-app/editors.mir24.tv/shared/public/uploaded
    dbhost: 127.0.0.1
    dbname: mir24_7
    dbuser: mir24_admin
    dbpass: !xoo8ao5ahz8mooxie2quohgh0Ungie
    dump_file: /home/www/dev7.mir24.tv/mir24_7.sql
    env_example_file: /home/www/dev7.mir24.tv/.env.frontend
