test-frontend:
    local: true
    stage: test
    roles: test
    repository: git@github.com:MIR24/frontend-server.git
    http_user: www-data
    deploy_path: /home/dmitry/Projects/mir24-deploy/frontend-server
    dbhost: 127.0.0.1
    dbname: mir24_7
    dbuser: root
    dbpass: example
    dump_file: /home/dmitry/Projects/mir24-deploy/mir24_7.sql
    env_example_file: /home/dmitry/Projects/mir24-deploy/.env.frontend

test-backend:
    local: true
    stage: test
    roles: test
    repository: git@github.com:MIR24/backend-server.git
    http_user: www-data
    deploy_path: &bsdeploy /home/dmitry/Projects/mir24-deploy/backend-server
    env_example_file: /home/dmitry/Projects/mir24-deploy/.env.backend

test-backend-client:
    local: true
    stage: test
    roles: test
    repository: git@github.com:MIR24/backend-client.git
    http_user: www-data
    deploy_path: /home/dmitry/Projects/mir24-deploy/backend-client
    back_server_path: *bsdeploy

test-photobank-client:
    local: true
    stage: test
    roles: test
    repository: git@github.com:MIR24/photobank-searchkit.git
    branch: external-client-dev
    http_user: www-data
    deploy_path: /home/dmitry/Projects/mir24-deploy/photobank-client
    back_server_path: *bsdeploy
