.test-base: &test-base
    hostname: dev7
    local: true
    stage: test
    roles: test
    keep_releases: 2
    branch: develop
    http_user: www-data

test-frontend:
    <<: *test-base
    repository: git@github.com:MIR24/frontend-server.git
    composer_action: update
    deploy_path: /home/www/dev7.mir24.tv/mir24.tv
    uploaded_path: /home/www/dev7.mir24.tv/editors.mir24.tv/shared/public/uploaded
    writable_mode: chown
    writable_use_sudo: true
    writable_dirs: [storage]
    shared_dirs: [storage/logs, public/uploaded]
    shared_files: []
    dbhost: 127.0.0.1
    dbname: mir24_7
    dbuser: root
    dbpass: example
    dump_file: /home/www/dev7.mir24.tv/mir24_7.sql
    env_example_file: /home/www/dev7.mir24.tv/.env.frontend

test-backend:
    <<: *test-base
    repository: git@github.com:MIR24/backend-server.git
    composer_action: update
    writable_mode: chown
    writable_use_sudo: true
    writable_dirs: [public/uploaded, storage]
    shared_dirs: [storage/logs, public/uploaded]
    shared_files: []
    deploy_path: /home/www/dev7.mir24.tv/editors.mir24.tv
    env_example_file: /home/www/dev7.mir24.tv/.env.backend

test-backend-client:
    <<: *test-base
    repository: git@github.com:MIR24/backend-client.git
    deploy_path: /home/www/dev7.mir24.tv/backend-client
    rsync_src: /home/www/dev7.mir24.tv/backend-client/release/build
    rsync_dest_release: /home/www/dev7.mir24.tv/editors.mir24.tv/release/public
    rsync_dest_current: /home/www/dev7.mir24.tv/editors.mir24.tv/current/public
    rsync:
        options: []
        flags: rzuEa
        include: []
        include-file:
        exclude: []
        exclude-file:
        filter: []
        filter-file:
        filter-perdir:

test-photobank-client:
    <<: *test-base
    repository: git@github.com:MIR24/photobank-searchkit.git
    branch: external-client-dev
    deploy_path: /home/www/dev7.mir24.tv/photobank-client
    rsync_src: /home/www/dev7.mir24.tv/photobank-client/release/dist
    rsync_dest: /home/www/dev7.mir24.tv/editors.mir24.tv/release/public/ftb
    rsync:
        options: [delete]
        flags: rzE
        include: []
        include-file:
        exclude: []
        exclude-file:
        filter: []
        filter-file:
        filter-perdir:

.prod-base: &prod-base
    hostname: dev3.mir24.tv
    user: barantaran
    stage: prod
    roles: test
    keep_releases: 2
    branch: master
    http_user: www-data

prod-frontend:
    <<: *prod-base
    repository: git@github.com:MIR24/frontend-server.git
    composer_action: install
    writable_chmod_mode: true
    writable_chmod_recursive: true
    writable_dirs: [storage/logs]
    shared_dirs: [storage/logs]
    shared_files: []
    deploy_path: /var/www/mir24-app/mir24.tv
    uploaded_path: /var/www/mir24-app/editors.mir24.tv/shared/public/uploaded
    clear_paths:
        - composer.json
        - composer.lock
        - .env.example
        - .git*
        - gulpfile.js
        - node_modules
        - package.json
        - package-lock.json
        - phpunit.xml
        - README.md
        - server.php
        - tests
        - travis.yml
    dbhost: 127.0.0.1
    dbuser: example_user
    dbpass: example
    dump_file: /home/www/dev7.mir24.tv/mir24_7.sql
    env_example_file: /home/www/dev7.mir24.tv/.env.frontend

prod-backend:
    <<: *prod-base
    repository: git@github.com:MIR24/backend-server.git
    composer_action: update
    writable_mode: chown
    writable_use_sudo: true
    writable_dirs: [public/uploaded, storage/logs]
    shared_dirs: [public/uploaded, storage/logs]
    shared_files: []
    deploy_path: /var/www/mir24-app/editors.mir24.tv
    writable: [public/uploaded]
    dbhost: 127.0.0.1
    dbuser: example_user
    dbpass: example
    env_example_file: /home/www/dev7.mir24.tv/.env.backend

prod-backend-client:
    <<: *prod-base
    repository: git@github.com:MIR24/backend-client.git
    deploy_path: /var/www/mir24-app/backend-client
    rsync_src: /var/www/mir24-app/backend-client/release/build
    rsync_dest: /var/www/mir24-app/editors.mir24.tv/release/public
    rsync:
        options: []
        flags: rzuEa
        include: []
        include-file:
        exclude: []
        exclude-file:
        filter: []
        filter-file:
        filter-perdir:

prod-photobank-client:
    <<: *prod-base
    repository: git@github.com:MIR24/photobank-searchkit.git
    branch: external-client-dev
    deploy_path: /var/www/mir24-app/photobank-client
    rsync_src: /var/www/mir24-app/photobank-client/release/dist
    rsync_dest: /var/www/mir24-app/editors.mir24.tv/release/public/ftb
    rsync:
        options: [delete]
        flags: rzE
        include: []
        include-file:
        exclude: []
        exclude-file:
        filter: []
        filter-file:
        filter-perdir:
