.test-base: &test-base
    hostname: dev7
    local: true
    stage: test
    roles: test
    keep_releases: 2
    branch: develop
    http_user: www-data

test-frontend:
    <<: *test-base
    repository: git@github.com:MIR24/frontend-server.git
    composer_action: update
    deploy_path: /home/www/dev7.mir24.tv/mir24.tv
    uploaded_path: /home/www/dev7.mir24.tv/editors.mir24.tv/shared/public/uploaded
    writable_mode: chown
    writable_use_sudo: true
    writable_dirs: [bootstrap/cache, storage]
    shared_dirs: [storage/logs, public/uploaded]
    shared_files: []
    db_app_host: 127.0.0.1
    db_app_name: mir24_7
    db_app_user: root
    db_app_pass: example
    db_dep_user: deploy
    db_dep_pass: example
    sphinx:
        host: 127.0.0.1
        port: 9312
        prefix: mir24_
    dump_file: /home/www/dev7.mir24.tv/mir24_7.sql
    env_example_file: /home/www/dev7.mir24.tv/.env.frontend

test-backend:
    <<: *test-base
    repository: git@github.com:MIR24/backend-server.git
    composer_action: update
    writable_mode: chown
    writable_use_sudo: true
    writable_dirs: [public/uploaded, storage]
    shared_dirs: [storage/logs, public/uploaded]
    shared_files: []
    deploy_path: /home/www/dev7.mir24.tv/editors.mir24.tv
    env_example_file: /home/www/dev7.mir24.tv/.env.backend

test-backend-client:
    <<: *test-base
    repository: git@github.com:MIR24/backend-client.git
    deploy_path: /home/www/dev7.mir24.tv/backend-client
    rsync_src: /home/www/dev7.mir24.tv/backend-client/release/build
    rsync_dest_release: /home/www/dev7.mir24.tv/editors.mir24.tv/release/public
    rsync_dest_current: /home/www/dev7.mir24.tv/editors.mir24.tv/current/public
    rsync:
        options: []
        flags: rzuEa
        include: []
        include-file:
        exclude: []
        exclude-file:
        filter: []
        filter-file:
        filter-perdir:

test-photobank-client:
    <<: *test-base
    repository: git@github.com:MIR24/photobank-searchkit.git
    branch: external-client-dev
    deploy_path: /home/www/dev7.mir24.tv/photobank-client
    rsync_src: /home/www/dev7.mir24.tv/photobank-client/release/dist
    rsync_dest: /home/www/dev7.mir24.tv/editors.mir24.tv/release/public/ftb
    rsync:
        options: [delete]
        flags: rzE
        include: []
        include-file:
        exclude: []
        exclude-file:
        filter: []
        filter-file:
        filter-perdir:

.prod-base: &prod-base
    hostname: dev3.mir24.tv
    user: barantaran
    stage: prod
    roles: test
    keep_releases: 2
    branch: master
    http_user: www-data

prod-frontend:
    <<: *prod-base
    repository: git@github.com:MIR24/frontend-server.git
    composer_action: install
    writable_chmod_mode: true
    writable_chmod_recursive: true
    writable_dirs: [bootstrap/cache, storage]
    shared_dirs: [storage/logs]
    shared_files: [storage/.htpasswd]
    deploy_path: /var/www/mir24-app/mir24.tv
    uploaded_path: /var/www/mir24-app/editors.mir24.tv/shared/public/uploaded
    clear_paths:
        - .env.example
        - phpunit.xml
        - README.md
        - server.php
        - travis.yml
    db_source_host: 127.0.0.1
    db_source_name: mir24_n1
    db_source_user: example_user
    db_source_pass: example
    db_app_host: 127.0.0.1
    db_app_user: example_user
    db_app_pass: example
    sphinx:
        host: 127.0.0.1
        port: 9312
        prefix: mir24_
        config: /var/www/mir24-app/mir24.tv/current/extconfig/sphinx.conf
###  You can use custom commands instead of deploy:writable as shown below
#    admin_commands:
#        - "command1"
#        - "command2"
    dump_file: /home/www/dev7.mir24.tv/mir24_7.sql
    env_example_file: /home/www/dev7.mir24.tv/.env.frontend

prod-backend:
    <<: *prod-base
    repository: git@github.com:MIR24/backend-server.git
    composer_action: update
    writable_mode: chown
    writable_use_sudo: true
    writable_dirs: [public/uploaded, storage]
    shared_dirs: [public/uploaded, storage/logs]
    shared_files: []
    deploy_path: /var/www/mir24-app/editors.mir24.tv
    db_app_host: 127.0.0.1
    db_app_user: example_user
    db_app_pass: example
    env_example_file: /home/www/dev7.mir24.tv/.env.backend

prod-backend-client:
    <<: *prod-base
    repository: git@github.com:MIR24/backend-client.git
    deploy_path: /var/www/mir24-app/backend-client
    rsync_src: "{{release_path}}/build"
    rsync_dest_base: /var/www/mir24-app/editors.mir24.tv
    rsync_dest_relative: public
    rsync:
        options: []
        flags: rzuEa
        include: []
        include-file:
        exclude: []
        exclude-file:
        filter: []
        filter-file:
        filter-perdir:

prod-photobank-client:
    <<: *prod-base
    repository: git@github.com:MIR24/photobank-searchkit.git
    branch: external-client-dev
    deploy_path: /var/www/mir24-app/photobank-client
    rsync_src: "{{release_path}}/dist"
    rsync_dest_base: /var/www/mir24-app/editors.mir24.tv
    rsync_dest_relative: public/ftb
    rsync:
        options: [delete]
        flags: rzE
        include: []
        include-file:
        exclude: []
        exclude-file:
        filter: []
        filter-file:
        filter-perdir:
